//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BefunCompileTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BefunCompileTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vvv:           &lt;           &lt;
        ///1&gt; 1+:::3/3*-!#^_&gt;::5/5*-!#^_v
        ///1$v          &gt;# v#      &gt;# v#&lt;
        ///1 &gt;:5558***-!|v$&lt;&gt;+\:1-!|v$&lt;
        ///&gt;^           &lt;&gt;$$^\     &lt;&gt;.@.
        /// </summary>
        internal static string testdata_001 {
            get {
                return ResourceManager.GetString("testdata_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v&gt;v&gt;ppp 0&gt;&gt;$ 10g20g:10p+:v
        ///202 &gt;00p0^|-*2/2::&lt;  vp02&lt;
        ///0::0^+ g00&lt;v**&quot;}P  &quot;:&lt;
        ///:1&gt;^@$.g00&lt;&gt;*` #v_^
        ///&gt;^        ^     &lt;.
        /// </summary>
        internal static string testdata_002 {
            get {
                return ResourceManager.GetString("testdata_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 89197939490919v          &gt;00g10g1-:10p%#v_10g:30p1-40pv
        ///v+*29191929891&lt;          ^    &lt;         &lt;_v#!  %g04g03&lt;
        ///&gt;*+*+*+*+*+*+*v &gt;&quot;{.i &quot;+**10p#^ #p #0 #0 &lt;&gt;40g:1-40p2-|
        ///              &gt;#^ +# *# +# *# +# *# +# *# +#    &lt;@.g03&lt;.
        /// </summary>
        internal static string testdata_003 {
            get {
                return ResourceManager.GetString("testdata_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45*00p110p120p &gt;10g20g*10p00g20g1+:20p`#v_10g.@ 
        ///               ^_v#`g00p03+1:g03   &lt;p031&lt;         v &lt;
        ///                 &gt;10g30g%          |1              &lt;^        p01/g03g01&lt; 
        ///                                   &gt;10g30g/40p150p  &gt; 20g50g1+:50p` #v_^
        ///                 ^                                &lt; |!%g05g04        &lt;
        ///                                                   ^&lt;.
        /// </summary>
        internal static string testdata_005 {
            get {
                return ResourceManager.GetString("testdata_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;d&quot;10p000p&gt;10g:00g+00p1-:#v_$010p&gt;&quot;c&quot;10g::1+:*\:5:+%\5:+/6+p`#v_       v
        ///&gt;$.@      ^            p01&lt;      ^                   p01+1g01 &lt;        0
        ///     &gt;                                   v
        ///|!:\&lt;|p01-1:g01&lt;$$_v#!:g+6/+:5\%+:5:g01 :&lt; p01&quot;c&quot;+&lt;_v#!p01:-1g01&lt;p01:g0&lt;
        ///\   ^&lt;             &gt;` &gt;                 #v_v
        ///&gt;         v            v-g+6/+:5\%+:5:g01&lt;          &gt;00g        ^
        ///##########&gt;                                       ^
        ///##########             &gt;010g:5:+%\5:+/6+pv
        ///##########                           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_006 {
            get {
                return ResourceManager.GetString("testdata_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;v&quot;00p54*:10p552**:20p*30p85+40p050p060p070p080p    v
        ///&gt;150g60p&gt;60g:20g%\20g/9+g&quot;0&quot;-*60g1+:60p50g-40g-#v_:80g`#v_$&gt;50g1+:50p30g-#v_ 970p &gt;70g0g.70g8-40g-#v_&quot;=&quot;,80g.@
        ///        ^                                       &lt;   $      ^                                                       &lt;
        ///                                                        &gt;80p060p&gt;60g50g+:2 0g%\20g /9+g&quot;0&quot;-60g9+0p6 0g1+:60p40g-#v_^
        ///^                                                   &lt;                     &lt;       ^p07+1g07        &lt;          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_008 {
            get {
                return ResourceManager.GetString("testdata_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v             v                                             &lt;
        ///&gt;&quot;4&quot;2/:*1-00p &gt; 000g: &quot;4&quot;2/ %&quot;?&quot;+\ &quot;4&quot;2/ /1+ p  00g:1-00p  #^_v++++++++++++++++++++++++++
        ///                                                               ++++++++++++++++++++++++++
        ///                                                               ++++++++++++++++++++++++++
        /// 08 02 22 97 38 15 00 40 00 75 04 05 07 78 52 12 50 77 91 08 | +++####################+++
        /// 49 49 99 40 17 81 18 57 60 87 17 40 98 43 69 48 04 56 62 00 | +++################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_011 {
            get {
                return ResourceManager.GetString("testdata_011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v     // Project Euler - Problem 13
        ///      37107287533902102798797998220837590246510135740250
        ///      46376937677490009712648124896970078050417018260538
        ///      74324986199524741059474233309513058123726617309629
        ///      91942213363574161572522430563301811072406154908250
        ///      23067588207539346171171980310421047513778063246676
        ///      89261670696623633820136378418383684178734361726757
        ///      28112879812849979408065481931592621691275889832738
        ///      44274228917432520321923589422876796487670272189318
        ///      47451 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_013 {
            get {
                return ResourceManager.GetString("testdata_013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        /// 000000000000000000000                                  
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000000
        /// 000000000000000000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_015 {
            get {
                return ResourceManager.GetString("testdata_015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000000
        ///v00000000000000000000000000000000000000000000000000000000001
        ///
        ///&gt; &quot;0&quot;:::::00p01p02p03p04p05p v  // INIT
        ///v  p64*8&quot;}&quot;p60*p62:6p61:&quot;&lt;&quot;  &lt;v p66-1g66                &lt;
        ///       &gt;06g1-66p             0&gt; 66g16g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_016 {
            get {
                return ResourceManager.GetString("testdata_016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///033544355436688779886
        ///0366555766
        ///$
        ///$   v-1           &lt;    v-1          &lt;
        ///&gt;54*&gt;:::1g&quot;0&quot;-\1p#^_54*&gt;:::2g&quot;0&quot;-\2p|
        ///v                       **25&quot;d&quot; 0 $$&lt;
        ///v                                              &lt;
        ///   v            $&lt;   &gt;:55+/2g\55+%           v
        ///:              &gt;:54*`|         &gt;&quot;d&quot;/1g70     v
        ///&gt;0\&gt;:!#v_:&quot;d&quot;\`| ^0g1&lt;  &gt;:&quot;d&quot;%!|        v    &lt;
        ///v      &lt;       &gt;:&quot;}&quot;8*-#^_$380v&gt;:&quot;d&quot;/1g\ &quot;d&quot;%v
        ///   ^                          &lt;         &lt;\3\7&lt;
        ///&gt;+# \:# _+          \ 1-                      :|
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_017 {
            get {
                return ResourceManager.GetString("testdata_017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $$&gt;53* 00p00g1-20p010p&gt;10g3*:20g1+g&quot;0&quot;-55+*\1+20g1+g&quot;0&quot;-+10g20g1+p10g1+:10p20g-1-#v_20g:1-20p010p#v_v
        ///75                    ^                                                           &lt;               &lt; v
        ///95 64                 v                                                                             &lt;
        ///17 47 82                                                                 &gt; $v
        ///18 35 87 10           &gt;00g2-:10p20p&gt;10g20g1+g10g20g2+g:10g1+20g2+g -:0`&gt;#^_-&gt;+10g20g1+p10g:1-10p#v_20g:1-:20p10p#v_01g.@
        ///20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_018 {
            get {
                return ResourceManager.GetString("testdata_018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v303232332323
        ///v313232332323
        ///6
        ///&gt;2*&gt;::0g&quot;0&quot;-47*+\0p::v
        ///   |:-1p1\+*74-&quot;0&quot;g1 &lt;
        ///v $&lt;
        ///&gt;202p112p122p&quot;2&amp;&quot;*1+32p092pv
        ///v20+1g20p29+g29!+-1g21%7g20&lt;&gt;#       0# v#   &lt;      &gt;                 &gt;v
        ///&gt;p12g1+12p32g4%             |       &gt;1 &gt;&gt;22g\g12g1--|
        ///                            &gt;32g&quot;d&quot;%|  0^ &lt;  #      &gt;112p22g:1+22p66+-| 
        ///                          v%*4&quot;d&quot;g23&lt;&gt;#^_1^  |-+1*&quot;(2&quot;g23&lt;p23+1g23p221&lt; 
        ///                          &gt;          ^&gt;1^    &gt;92g.@      ^             &lt;.
        /// </summary>
        internal static string testdata_019 {
            get {
                return ResourceManager.GetString("testdata_019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
        ///v0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001
        ///&gt;&quot;d&quot;&gt;1-:!#v_:03p013p&quot;~I&quot;+23p&gt;23g&quot;d&quot;%1+23g&quot;d&quot;/g&quot;0&quot;-03g*13g+:55+%68 v
        ///    ^     $#               _^#!p32:-1g32p31/+55p/&quot;d&quot;g32+1%&quot;d&quot;g32+*&lt;
        ///          &gt;&quot;~I&quot;+33p0&gt;33g&quot;d&quot;%1+33g&quot;d&quot;/g&quot;0&quot;-+  33g:1-33p v
        ///                 @._^#!                                &lt;.
        /// </summary>
        internal static string testdata_020 {
            get {
                return ResourceManager.GetString("testdata_020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v0123456789
        ///&gt;&quot;ddd&quot;**1v
        ///vp129p11-&lt;
        ///       &gt;v&gt;v     v     &lt;  v    &lt;   &gt;  v   &gt;\1-\vv    p14+1g14&lt;
        ///&gt;21g:1+|&gt;|&gt;21g0\&gt;:1-:#^_$&gt;*\:#^_$:|  &gt;31p 141p &gt;31g41g*11g`!|
        ///       $                          &gt;$1^   |-&quot;x&quot; g0:\&lt;\1&lt;g14  &lt;
        ///       @ &gt;                              v&gt;    &gt;1+\:|  1
        ///^p12-1g12p11-*-1g14g13g11.p0\&quot;x&quot;\-&quot;0&quot;g0:&gt;#- #1 #$ #&lt;  ^.
        /// </summary>
        internal static string testdata_024 {
            get {
                return ResourceManager.GetString("testdata_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///####################################################################################################
        ///####################################################################################################
        ///####################################################################################################
        ///####################################################################################################
        ///####################################################################################################        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_026 {
            get {
                return ResourceManager.GetString("testdata_026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;d&quot;55+*1+::1-01p*&gt;:01g-:01g-:01g-:01g-:1-#v_&gt;+\:#&lt;_$.@
        ///X                ^p10-2g10                &lt;.
        /// </summary>
        internal static string testdata_028 {
            get {
                return ResourceManager.GetString("testdata_028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v#########
        /// ###
        ///
        ///&gt;00000000010p20p30p40p50p60p70p80p90p  &quot;d&quot;2*  11p921p031p 0v
        ///v                                                         $&lt;
        ///             vp0p12:+1g120&lt;  &gt;g25**+70g5*+80g2*+90g+v       
        ///&gt;21g0g1+21g0p&gt;21g9-       |&gt;10g5&quot;d&quot;**20g2&quot;d&quot;**+&quot;d&quot;3v&gt;:11g\`|
        ///p                         &gt;^ ^6+**45g05+*&quot;2&quot;g04+*g0&lt;v&lt;     
        ///^12-1&lt;                              v&lt;      v       &lt;|-g11 &lt;
        ///     |                           -1:&lt;|g0:g12&lt;p13+1g13&lt;
        ///     &gt;$31g.@                         &gt;1-21p ^.
        /// </summary>
        internal static string testdata_031 {
            get {
                return ResourceManager.GetString("testdata_031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///&gt;110p120p&quot;cc&quot; v
        ///vp09p08       &lt;     &gt;80g55+/90g55+/-#v_v                           
        ///&gt;90g80g`!#v_&gt;80g55+/|                  &gt;80g90g55+/*90g80g55+/*-#v_v
        ///            v       &lt;                &lt;                          &lt;
        ///                    &gt;80g55+/90g55+%-#v_v
        ///            &gt;80g55+/|                  &gt;80g90g55+/*90g80g55+%*-#v_v
        /// @v\p05:&lt;   v       &lt;                &lt;                          &lt;  
        /// .&gt;50g%:|: &lt;        &gt;80g55+%90g55+/-#v_v
        /// ^/\g02$&lt;  g&gt;80g55+%|                  &gt;80g90g55+%*90g80g55+/*-#v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_033 {
            get {
                return ResourceManager.GetString("testdata_033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v      
        ///0             v                      \&lt;     v            *2\&lt;     &gt;:.55+,\   v
        ///&gt;093194*+**&gt;::&gt;55+*10p:55+%10g+\55+/:#^_$::0&gt;10p:2%10g+\2/:#^_$-!#^_$        v
        ///           |:-1                                                              &lt;
        ///v          &lt;     v                      \&lt;     v            *2\&lt;     &gt;:.55+,\v
        ///&gt;93194*+**&gt;::55+/&gt;55+*10p:55+%10g+\55+/:#^_$::0&gt;10p:2%10g+\2/:#^_$-!#^_$     v
        ///          |:-1                                                               &lt;
        ///          &gt;&quot;= &quot;,,&gt;+\:#&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_036 {
            get {
                return ResourceManager.GetString("testdata_036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v#########
        ///v#########    v                                                                                                                                              &lt;#     p145&lt;
        /// #########         v          +1&lt;           v            &lt;  v               &lt;                 vp2\0:&lt;         &gt;v    &gt;v          &gt;$v   v\g2:&lt;
        ///&gt;&quot;ec&quot;*31p&gt;241p&gt;01-1&gt;:31g*\:41g-#^_$&gt;\10p01-\&gt;:55+%\55+/:#^_$&gt;10g55+*+10p:1+#^_$10g\:1+#v_$:55+&gt;  1-:|  &gt;:55+%:|&gt;:2g!|&gt;1\2p55+/:!| &gt;55+&gt; 1-:|&gt;#v_$41g1-:41p1-#^_31g1-:31p|
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_038 {
            get {
                return ResourceManager.GetString("testdata_038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///&gt;010p020p630p&quot;d&quot;55+*90p050p30g3/70p         v
        /// vp07/3g03p050                                                    p03+2&lt;
        ///v                     &gt;#        v# p07-1&lt;           &gt;10p30g20pv
        ///&gt;30g::270g*-*\70g-2*%#^_50g1+50p&gt;70g:2-#^_$50g:10g`#^_$       &gt;30g:90g-|
        /// &gt;                             $^$          &lt;                    @.g02$&lt;.
        /// </summary>
        internal static string testdata_039 {
            get {
                return ResourceManager.GetString("testdata_039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        ///&gt;01:55+*:55+*:55+*:55+*:55+*:55+*130p v
        ///         v                                           &lt;
        ///&gt;110p120p&gt;:10g920g**`!#v_10g920g**-10g1+10p20g55+*20p^&gt;v          &lt;
        ///  &gt;30g.@               &gt;1-:10g/20g+\      10g%10g\-1-:|&gt;\55+/\1-:#^_v
        ///  $                                   $               &gt;           :^
        ///^_^#:                                 &lt;#                p03*g03%+55$&lt;.
        /// </summary>
        internal static string testdata_040 {
            get {
                return ResourceManager.GetString("testdata_040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vXXXXXX
        ///vXXXXXX
        ///$
        ///&gt;7  12p 0&gt;:0\1p::&quot;1&quot;+v     
        ///         |-g21:+1p0\ &lt;
        ///v   p231$&lt;
        ///              &gt;32g1gv
        ///        &gt;32g2%| vp24&lt;&gt;2g1g1+32gv 
        ///&gt;32g:1g`|     &gt;0    ^^3p0g23p0&lt;1
        ///^       &gt;032g1pv&gt;42g0g32g0g42g^p
        ///^p23+1g23      &lt;          vp230&lt;
        ///     v6:-1g26*+ 55&lt;0p26g21&lt;          @.&lt;
        ///     &gt;2p0g&quot;0&quot;-+62g|                    $
        ///               #  &gt;:&gt;302pv &gt;:02g2-:*` !|
        ///               $    &gt;!\2% +|%p20+1:g20:&lt;
        ///                    ^`2::&lt; $  
        ///               ^           &lt;.
        /// </summary>
        internal static string testdata_041 {
            get {
                return ResourceManager.GetString("testdata_041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                               v ################################################################################
        ///                                ################################################################################
        ///A                               ################################################################################
        ///ABILITY                         ################################################################################
        ///ABLE                            ######################## [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_042 {
            get {
                return ResourceManager.GetString("testdata_042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vXXXXXXXXX
        ///vXXXXXXXXX
        ///
        ///&gt;902p012p9&gt;:0\1pv
        ///          |\-1: &lt;
        ///&gt;12g55+, #$ &quot; =&quot;,, . @                                       vp20&lt;
        ///|`9g20    &lt;                                                  &lt;  &lt;
        ///             &gt;$0v        &gt; v                         &gt;002g0g&quot;0&quot;-1p v
        ///&gt;02g0g&quot;0&quot;-:9`|  &gt;:22p55+-| &gt;22g1g     #v_ 02g0g&quot;9&quot;`!#^_         ## v
        ///             &gt;1+^        &gt;0|-9p22+1:g22&lt;vp20-1g20p0g20+&quot;0&quot;g22p1g221&lt;
        ///v!`g200                                 &lt;             p20+1g20&lt; ##
        ///                           &gt;  02g0g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_043 {
            get {
                return ResourceManager.GetString("testdata_043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v                 &gt;v
        ///&gt;8::**::**8*:*20pv0v&gt;vv p03+g03*2:p01-\g01+g03:&lt;
        ///v           +&quot;l#&quot;&lt;3pp2# v/4    &lt;   &gt;:30g+10g`! |
        ///&gt;1+::2*1-*64**v   010&gt;0g&gt;:10g`#^_&gt;:|:/4p03/2g03&lt;
        ///^        &lt;  $&lt;&gt;1+:^&gt;^ &gt;30g2/30p4/^ &gt;$30g:*-v
        ///@.*-1*2:_^#!_^#!                    -5%6g03&lt;.
        /// </summary>
        internal static string testdata_045 {
            get {
                return ResourceManager.GetString("testdata_045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v   v0p01**&lt;  &gt;:30p::&gt;20p\1-:  #v_$$v
        ///5&gt;8#&lt;&quot;}&quot;* #*&gt;:|      ^%g01*g02:\&lt;   2
        ///&gt;5+:::*:*: ^^-&gt;# $# .# @#1g03%g01+g0&lt;.
        /// </summary>
        internal static string testdata_048 {
            get {
                return ResourceManager.GetString("testdata_048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v?&gt;:55+%2+\55+/:5v&gt;&quot;Z%&quot;v&gt;+\55+/:55v&gt;v v           0`*&quot;ce&quot;:+*&quot;Z%&quot;$&lt;
        ///&quot; :v55:/+55\+2%+5&lt;\  v&lt;*2v+55\+2%+&lt;:v&gt;$:.48*,&quot;Z%&quot;*+:.48*,&quot;Z%&quot;*+. @
        ///( :&gt;+%2+\55+/2+***^  01+%/&gt;* -#v_-!|:|&lt;                          #
        ///%   v5:/+55\+2%+55::g&lt;:1+2*    v   &lt;&quot;&gt;::2%!#v_v &gt;10g\%!#v_:10g2/`|
        ///&quot;   &gt;5+%2+\55+/:55v   p05+*    $   ve#&lt; v%3:&gt;#&lt;#^ #&lt;    &gt;    v   :
        ///* +v***+2/+55\+2%+&lt;   ^&lt;5&gt;^    $    c`  &gt; !#^_10p7:^:+6_^#%\g01-2&lt;
        ///7 1&gt;\&quot;Z%&quot;*+:55+%2+\55+/:^      v   &lt;&quot;*^                   $$$&lt;
        ///&gt;+^                            &lt;    &gt;^.
        /// </summary>
        internal static string testdata_049 {
            get {
                return ResourceManager.GetString("testdata_049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55+&gt;v&gt;v&gt;5+/&gt;::103p55+*&gt;55+/        :#v_$212pv
        ///XX  :6/5 &gt;  ::103p55+*^p30*g30+2%+55:&lt;      :
        ///XX  0:1:  v$_v#!:       /+55&lt;*+55p311* &lt;g21 &lt;
        ///XX  1p1p  1  &gt;:55+%2+13g*13p^     &gt;:12g^
        ///  &gt;^&gt;^&gt;^  &gt;3g03g-   #v_12g1+:12p7-|
        ///  ^*+55$_^#!`\g11:+1$&lt;        @$$.&lt;.
        /// </summary>
        internal static string testdata_052 {
            get {
                return ResourceManager.GetString("testdata_052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v ###    ####################################################
        ///         ####################################################
        ///&gt;190p191p020p130pv                 &gt;40g9+30g2%!g40g8+30g2%!g+vv!g!%2g03+9g04`**&lt;
        ///&gt;30g:&quot;d&quot;-!#v_1+:30p2/40p&gt;30g40g2*&gt;-|                         &gt;:40g9+30g2%p&quot;}}@&quot;^
        ///^          &gt;#&lt;$ #&lt;20g.@            &gt;40g8+30g2%!g2*           ^&gt;$40g9+1-30g2%!g!v
        ///                      &gt;30g40g2* -^v                                _v#!_v#!_v#!&lt;
        ///             ^       _^#!p04:-1g04&lt;p%2g03+9g040p02++1!!-*2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_053 {
            get {
                return ResourceManager.GetString("testdata_053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v                           v-1\+g02&lt;
        ///0          v/+55\+g01\p01%+&lt;        $  v/+55\+g01\p01%+&lt;
        ///&gt;&quot;}P&quot;*&gt;::0\&gt;:!#v_\55+*\:55 ^&gt;:!#v_\::0\&gt;:!#v_\55+*\:55 ^
        ///    &gt;$ .@      &gt;$+38*   #v  ^#   &lt;  |-p02:$&lt;            
        ///    ^_^#!:-1             &lt;\+1\$$&lt;^$$&lt;                   
        ///        
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///
        ///[10] GetReversed() - temp
        ///[20] IsLychrel     - reversed number
        ///
        ///
        ///
        ///47*7*      =&gt;    196
        ///&quot;2&quot;        =&gt;     50
        ///&quot;}P&quot;*      =&gt; 10 000
        ///
        ///
        ///
        ///// GetNumberReversed()  stack-&gt;stack
        ///
        ///  v/+55\+g01\p01%+&lt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_055 {
            get {
                return ResourceManager.GetString("testdata_055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v####
        ///v##
        ///v#
        ///v###     &gt;             &gt;             &gt;      &gt;$0v  
        ///                &gt;             &gt;              $1v  
        ///  &gt;::2\`#^_:2-!#^_:2%!#^_:9\`#^_:3%!#^_:5%!#^_1 :v
        ///2&gt;^&lt;v\                      p21:+1g21:_v#-3 &lt;p2 1&lt;
        ///1  p&gt;:11p1-0\&gt;:2% !#v_v    v ++!!+1-g&lt; #    ^ &lt; &gt;v
        ///3  3         ^\+1\/2&lt; \    &gt;3-#v_$$  1&gt;12g\  !|&gt;|
        ///p 31 vp01p03p04 g11p12&lt;        &gt;:*11v1 &gt;$1   #$^
        ///1 p+ &gt;120pv        v%g04*&lt;v-1\    %g&lt;^ \!!-1:&lt;$0
        ///2 32 vg030&lt;  v-1\  &lt; &gt;10g^   &gt;\:::*11  g%1-!\^&gt;^
        ///3 3g     &gt;$1\&gt; :#v_ $ 21g &gt;:#^_$1-! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_058 {
            get {
                return ResourceManager.GetString("testdata_058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v$$  ### ---------------------------------------------------------------- ###
        /// $$  ### ---------------------------------------------------------------- ###
        /// $   ### ---------------------------------------------------------------- ###
        /// $   ### ---------------------------------------------------------------- ###
        /// $   ### ---------------------------------------------------------------- ###
        ///     ### ---------------------------------------------------------------- ###
        ///     ### ----------------------------- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_061 {
            get {
                return ResourceManager.GetString("testdata_061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v XXXX   #######################################################################
        ///  XX
        ///                          v1\1p12::+1   \+g2&lt;
        ///0                 v9p03p02&lt;         \g12:+1&lt;^2\p22_v
        ///1          &gt;v     v              &lt;  v-\&quot;P&quot;&lt;       :$
        ///&gt;        :v1v&gt;0p&gt;9&gt;:&quot;0&quot;\0p1+:&quot;O&quot;-|&gt;:0g&quot;0&quot;-||!`g12&lt;-$
        ///          :p\3v p050p04&quot;O&quot;&lt;p0\&quot;1&quot;&lt;^+&gt;#1 $#&lt; :21g-|\.
        ///          211p&gt; 40g0g&quot;0&quot;-2 0g*50g+:55+%&quot;0&quot;v&gt;$55+0v+@
        ///          &gt;^20|-8p04:-1g04 p05/+5 #5p0g04+&lt;&gt;5#$5#&lt;^
        ///            &gt;^&gt;30g1-:30p #^_9     ^.
        /// </summary>
        internal static string testdata_063 {
            get {
                return ResourceManager.GetString("testdata_063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v###
        /// #####
        ///0
        ///&quot;&gt;&gt;1-:0\951p11p021p131v      v12g14    p150 p13/g&lt;
        ///I       vp01g03_v#-g01:_v#- &lt;&gt;g+31g/ :31g*21g-21v1
        ///i   @   &gt;:30p:20 g\/+2/: 30g^^12p14:&lt;&gt;11g21g:*-3 ^
        /// *  .           &gt;    #$ &gt;$30g::*11g-||+g15-1g13p&lt;
        ///&quot;+  $   ^p02:p010g11p1&lt;       v\+1\&lt;&gt;&gt;0&gt;\#+ #1:#$_v
        ///&gt;^^_^#-2:                     &lt;   _^#          %2$&lt;.
        /// </summary>
        internal static string testdata_064 {
            get {
                return ResourceManager.GetString("testdata_064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v $$$    #######################################################################
        ///
        ///         #######################################################################
        ///
        ///    v                 -1&lt;
        ///&gt;&quot;F&quot;&gt;:9+&quot;0&quot;\0p:9+&quot;0&quot;\2p:|
        ///v&quot;c&quot;p040p2&quot;O1&quot;p0&quot;O0&quot;   $&lt;
        ///          &gt;$1         v@.&lt;v02-&quot;0&quot;p0g03:g2g03-&quot;0&quot;g0:p03:&lt;-1&lt;
        ///  &gt;:1-3%:!|   &gt;:1+3/2*v  +&gt;g*+40g+:55+%&quot;0&quot;+30g2p55+/40p:9-|
        ///&gt;:|       &gt;2-#^_1     &gt;20 p                      &quot;O&quot;v  #  $
        ///| &gt;# #+ #1 #: #- #12# ^#                            &gt;# ^# &lt;
        ///$               &gt;\v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_065 {
            get {
                return ResourceManager.GetString("testdata_065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &gt;&quot;d&quot; 00p00g1-20p010p&gt;10g3*:20g1+g&quot;0&quot;-55+*\1+20g1+g&quot;0&quot;-+10g20g1+p10g1+:10p20g-1-#v_20g:1-20p010p#v_v
        ///59                    ^                                                           &lt;               &lt; v
        ///73 41                 v                                                                             &lt;
        ///52 40 09                                                                           &gt; $v
        ///26 53 06 34           &gt;00g2-:10p  20p &gt; 10g20g1+g  10g20g2+g  :  10g1+20g2+g -:0`&gt;#^_-&gt; + 10g20g1+ p   10g:1-10p#v [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_067 {
            get {
                return ResourceManager.GetString("testdata_067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v  X   X ##########
        ///     X   OOOOOOOOOO
        ///&gt;&quot;:&quot;v   v                           &lt; &lt;
        ///v   &lt;   vp1+9-&quot;0&quot;g0+9p03:-1g03&quot;O&quot;    &lt;
        ///&gt;90p030p&gt;30g9+0g1-:30g9+0p&quot;0&quot;-:70p0\`|
        ///v   g03_^#!         -&quot;O&quot;g1+9g07     #&lt;$
        ///&gt;:#v_70g5`                           &gt;|
        ///v-1&lt; v  _v#!`g039$                    &lt;
        ///&gt;:#v_     70g9-!                     ^
        ///v-1&lt;     &gt;&quot;X&quot;70g9+1p&quot;:&quot;30g1+:30p9+0p^
        ///&gt;:#v_ 90+0g91+0g92+0g++51p70g9-!     ^
        ///v-1&lt; &gt;91+0g&quot;/&quot;- 98+0g&quot;/&quot;- 99+0g&quot;/&quot;- v
        ///&gt;:#v_90g&quot;0&quot;-70g`                     ^
        ///v-1&lt; v-&quot;/&quot;g0+79 -&quot;/&quot;g0+69 -&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_068 {
            get {
                return ResourceManager.GetString("testdata_068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v000000    // Project Euler - Problem 69
        ///################################################################################
        ///################################################################################
        ///################################################################################
        ///v                     &gt;p50g1+50pv                                         @.g07&lt;
        ///v                     ^1g0&lt;     &gt;30g1+:30p40g-       #v_&quot;}}@&quot;**60p   0&gt;:1g70g*v$
        ///&gt;170p&quot;P&quot;:10p3:20p*40p230pv^5g03_^#-&quot; &quot;g+1/g01\%g01:g03&lt;p050p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_069 {
            get {
                return ResourceManager.GetString("testdata_069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v X X C
        ///  X X ????
        ///
        ///&gt;020p040p121p141p&quot;}}@&quot;**60pv
        ///v0                         &lt;         &gt;01+*v
        ///&gt;1+ :3*7%!#v_:61p:3*7/:71p7*61g3*-:0`|    &gt;81p61g7*91p41g91g*21g81g*`#v_v
        ///|-g06:     &lt;                        &lt;&gt;01-*^v  p04g16p02g17p12g19p14g18&lt;
        ///&gt;$20g.&quot;/ &quot;,,55+,40g.@               ^      &lt;                            &lt;.
        /// </summary>
        internal static string testdata_071 {
            get {
                return ResourceManager.GetString("testdata_071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v  X OO    // Project Euler - Problem 76
        ///v
        ///v
        ///   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///   +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        ///   +++++++++++++++++++++++++++++++++++++ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_076 {
            get {
                return ResourceManager.GetString("testdata_076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v00000 00  // Project Euler - Problem 77
        /// XXXXXX
        ///#####################################################################################################
        ///
        ///#####################################################################################################
        ///#####################################################################################################
        ///#####################################################################################################
        ///############################################### [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_077 {
            get {
                return ResourceManager.GetString("testdata_077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v
        /// ++++++++++ 319 680 180 690 129 620 762 689 762 318
        /// ++++++++++ 368 710 720 710 629 168 160 689 716 731
        /// ++++++++++ 736 729 316 729 729 710 769 290 719 680
        /// ++++++++++ 318 389 162 289 162 718 729 319 790 680
        /// ++++++++++ 890 362 319 760 316 729 380 319 728 716
        /// ++++++++++
        /// ++++++++++ ##########
        /// ++++++++++
        /// ++++++++++ XXXXXXXXXX
        /// ++++++++++
        ///
        ///&gt;55+&gt;:1\:v&gt;:55+/1+30p:55+%4*66++20p020g0+30gg&quot;0&quot;-:50p66v
        ///    |:-1p&lt; v1g070p+1g07+1g062p+1g07+1g052p+1g06+1g052&lt; +
        ///    &gt;$ 77*^&gt;+50g1+p070g1+60g1vv&lt;        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testdata_079 {
            get {
                return ResourceManager.GetString("testdata_079", resourceCulture);
            }
        }
    }
}
